add text and tooltip for copy success msg
keploy/website pull request #16
Opened 2024-03-31 06:12 UTC by sk-pathan

fix:#1672

what pr do 
This pull request aims to enhance the user experience and streamline the development process by introducing two key features: "Try Deploy Locally" button and "Copy Tooltip for Success Message."

Changes Proposed:

Added "Try Deploy Locally" button to enable users to test deployments locally before committing changes.
Implemented a copy tooltip for success messages, providing users with clear feedback upon successful copy actions.

mobile view:
https://github.com/keploy/website/assets/141400463/c4f462ea-383a-4dc6-a47b-6adb55d56230

laptop view:

https://github.com/keploy/website/assets/141400463/5982f77b-d5f7-41fe-b83f-efc29b1772df

2024-03-31 06:16 UTC, sk-pathan commented
hey @nehagup and @Hermione2408 review my changes

2024-03-31 09:06 UTC, Hermione2408 commented
Hey @sk-pathan 
 It is breaking in medium size please check 
![Screenshot from 2024-03-31 14-30-29](https://github.com/keploy/website/assets/78696767/0669edbb-7070-4cf2-ad7c-1e3ef1f55b7a)
Also please use "try keploy locally" color according to theme mentioned in README

2024-04-01 04:38 UTC, sk-pathan commented
hey @Hermione2408 ,
I have fixed the issue and for colour of text i change the colour but you have better idea please let me know 
![image](https://github.com/keploy/website/assets/141400463/292dfeff-adcd-4c90-b3ef-25b8b72b3c04)

2024-04-01 11:38 UTC, Hermione2408 commented
Hey @sk-pathan  I noticed the second gif is overlapping in the medium size view. Also, there's inconsistency with the text color across different views; please make it consistent to text-secondary-300
![Screenshot from 2024-04-01 17-04-55](https://github.com/keploy/website/assets/78696767/2acd7f08-16b0-463b-85f7-427bcee59074)

2024-04-03 04:32 UTC, sk-pathan commented
hi @Hermione2408 have look on change

2024-04-03 06:20 UTC, Hermione2408 requested changes
![Screenshot from 2024-04-03 11-43-25](https://github.com/keploy/website/assets/78696767/c9632a6e-66ee-46b3-ba71-40cb31266c2d)
Hey @sk-pathan In medium size, now gif is not aligned with the side div

2024-04-03 06:20 UTC, Hermione2408 commented on components/features.tsx
> +      <p className='font-bold text-secondry-300'>Try Keploy Locally </p>
secondary*

2024-04-05 11:04 UTC, Hermione2408 requested changes
Hey due to fixed height to the image the gap in third gif is a lot in small screen can you make it more responsive? 
![Screenshot from 2024-04-05 16-30-06](https://github.com/keploy/website/assets/78696767/e3966adc-bfc7-4652-85cb-194e43437eac)

2024-04-05 11:04 UTC, Hermione2408 commented on components/features.tsx
> +      <p className='font-bold text-secondry-300'>Try Keploy Locally </p>
@sk-pathan please correct this spelling mistake the class is not getting applied

2024-04-10 06:54 UTC, sk-pathan commented
@Hermione2408 
![Screenshot 2024-04-10 113507](https://github.com/keploy/website/assets/141400463/b1720e08-9b92-44cb-a11e-15905aadd65a)
![Screenshot 2024-04-10 113441](https://github.com/keploy/website/assets/141400463/1efc5020-88d0-4d4e-b14a-35c2a4cbd46f)

2024-04-15 06:48 UTC, Hermione2408 commented
Hey @sk-pathan, this issue is now closed https://github.com/keploy/keploy/issues/1672. Thanks for your contributions I am closing this PR!

2024-04-15 06:48 UTC, closed without merging