Add new languages and New Frameworks.
keploy/website pull request #17
Opened 2024-04-01 04:45 UTC by Aditya-eddy

closes [#issue](https://github.com/keploy/keploy/issues/1734)
I have updated language to c# and rust.
If we need to update any new frameworks please do list them or any new languages we need to add.
![Screenshot from 2024-04-01 10-10-40](https://github.com/keploy/website/assets/70089590/13553802-33ea-4c5c-91dc-f91ef6eb1db1)

2024-04-01 10:49 UTC, Hermione2408 commented
Hey @Aditya-eddy, I think we should line them up in a single row you can consider slightly reducing their size to fit

2024-04-02 03:43 UTC, Aditya-eddy commented
How does this look?
![Screenshot from 2024-04-02 09-12-34](https://github.com/keploy/website/assets/70089590/ddff751d-1364-4b1c-a5b0-a20be87735cb)

2024-04-02 06:26 UTC, Hermione2408 commented
> How does this look? ![Screenshot from 2024-04-02 09-12-34](https://private-user-images.githubusercontent.com/70089590/318632491-ddff751d-1364-4b1c-a5b0-a20be87735cb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIwMzkyNDgsIm5iZiI6MTcxMjAzODk0OCwicGF0aCI6Ii83MDA4OTU5MC8zMTg2MzI0OTEtZGRmZjc1MWQtMTM2NC00YjFjLWE1YjAtYTIwYmU4NzczNWNiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAyVDA2MjIyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU1MjdiNTNkZTEyYjFiYzUxOWYyMGIyZWI2MTViOGVlM2M5YzE5ZWY3ZTU0YTIzYmZhNThjNGExOTA1YzQzODYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Fkzzqz7iWx6l5Kgo-TIuS7rHrhghhWFK10gHxBEhndQ)

This looks fine

2024-04-02 08:15 UTC, Aditya-eddy commented
Any new frameworks to be updated? 
@Hermione2408 , @nehagup

2024-04-02 09:32 UTC, Hermione2408 requested changes
Rust image is not looking centered align can you please check .Also you can add your command CLI space changes in this PR.

2024-04-02 09:32 UTC, Hermione2408 commented on components/language.tsx
> +          <div className="grid max-w-sm grid-cols-6 gap-7 mx-auto md:max-w-4xl md:grid-cols-6 place-content-center">
please reduce this gap looking too much in small screen

2024-04-03 03:55 UTC, Aditya-eddy commented
Does this changes look good?
![Screenshot from 2024-04-03 09-24-25](https://github.com/keploy/website/assets/70089590/de5da43d-7963-429d-9b6b-d97562e61720)
![Screenshot from 2024-04-03 09-16-39](https://github.com/keploy/website/assets/70089590/4446c6b4-0f91-4aad-8ce3-0893aedc95e8)

2024-04-03 06:26 UTC, Hermione2408 commented
Yes looks promising!

2024-04-03 08:33 UTC, nehagup commented
@Aditya-eddy please ensure that the language logos are centre aligned (vert and horse) and are within the same height.

2024-04-04 23:33 UTC, Aditya-eddy commented
Hey @nehagup I have commited the changes please check I think they look aligned in one row now!

2024-04-05 11:09 UTC, Hermione2408 requested changes

2024-04-05 11:09 UTC, Hermione2408 commented on components/language.tsx
> +                src="/images/frameworks/csharp.svg" // Assuming the image file extension is .jpg
the comment is irrelevant please remove them rest changes look fine!

2024-04-08 03:08 UTC, Aditya-eddy commented
Hey @Hermione2408 removed the comments!

2024-04-08 06:43 UTC, Hermione2408 approved these changes
LGTM @nehagup

2024-04-08 10:08 UTC, nehagup approved these changes

2024-04-08 10:08 UTC, merged