Adding webstories
keploy/website pull request #22
Opened 2024-04-09 23:25 UTC by Aditya-eddy

Adding feature for Web-Stories:
1. There will be Main Page of web-stories in which all the webstorie's card will be displayed.
2.  On clicking on the web-stories , the web-stories will be displayed.

Currrently Dummy Data is being used in form of static Array.
following 2 urls will be available for it:
1./webstories
2./webstories/[slug]

2024-04-10 04:23 UTC, its-kunal commented
Hey @Aditya-eddy, are there any blockers that I can help you with?

2024-04-12 07:57 UTC, Aditya-eddy commented
Hey @nehagup I have made /webstories , /webstories/[slug] 
1. /webstories
All the web-stories will be displayed here. There is searching on the basis of title. Currently thinking of adding category based filtering with widgets.
Please give feedback on what more elements should we add to it.
![Screenshot from 2024-04-12 13-24-22](https://github.com/keploy/website/assets/70089590/210ba724-b75c-488f-a93a-3527389ec121)
2./webstories/[slug[
I have added animations in loading-Stories Bar. And also if the Link are supplied there will be swipe link widget in it. I think I might be lacking in implementing the themes. Please guide on this.
![Screenshot from 2024-04-12 13-26-48](https://github.com/keploy/website/assets/70089590/42e96e6e-c269-4aee-9374-bdbcfb9c9fa5)

cc- @nehagup , @Hermione2408

2024-04-15 06:15 UTC, Hermione2408 reviewed
Hey @Aditya-eddy, the webstories component looks good! However, it should align more closely with Keploy's theme. Consider using the primary color and gradient for the loading-stories bar and background. For the label at the bottom, the secondary color mentioned in the readme would be a good fit. This should help everything blend seamlessly with the overall design.

2024-04-15 09:02 UTC, Aditya-eddy commented
> Hey @Aditya-eddy, the webstories component looks good! However, it should align more closely with Keploy's theme. Consider using the primary color and gradient for the loading-stories bar and background. For the label at the bottom, the secondary color mentioned in the readme would be a good fit. This should help everything blend seamlessly with the overall design.

Okay let me work it. Thanks for the feedback!!

2024-04-19 03:27 UTC, Aditya-eddy commented
hey @Hermione2408 I have worked on color scheme I'll attach the screenshot for ref. Also could you tell any more features that we need to implement in the homepage?

![image](https://github.com/keploy/website/assets/70089590/b1118dc3-c846-474a-a2d2-2c32ed17235e)

2024-04-19 10:24 UTC, Hermione2408 reviewed
Hey @Aditya-eddy Here are few suggestions:

- Consider displaying the search bar by default instead of just its icon, especially if it stands alone without tabs. Also Are you planning to include multiple sections for stories and keeping search icon for that purpose?
- It might be better for stories to open in a new tab. If not, adding a close icon to redirect users back to the web-stories page would be helpful.
- The 'show more' option is overlapping with the text on the last card. We could fix this by either creating a separate slide for it without any label or adjusting its position to avoid overlap.
- Introducing a default timeout, maybe around 30 seconds, for auto-changing stories could improve the experience. A pause button would be a great addition for user control.
- Does it support videos/gif also?

2024-04-19 10:54 UTC, Aditya-eddy commented
Hey @Hermione2408 let me work on the suggestion and get back to you!!

2024-04-28 11:31 UTC, Aditya-eddy commented
Hey @Hermione2408 
1. Yes I was thinking of displaying most used first five categories there so yes there would tabs based on the Categories.
2. Yes that's a great suggestion personally I think that opening to a new tab would be great!
3.Okay for each individual tabs show more option is optional it is possible to create a slide with no text but just show more. For more on this you can check data.ts Perhaps I will create a Readme for the data schema at the end.
4.OKay working out on the time-out.
5. Currently it does'nt support that but soon it will be!

2024-05-23 20:04 UTC, Hermione2408 requested changes
Hey @Aditya-eddy 

- The transition to next web story is not happening right now, Are you working on it?
- When the story is getting closed manually the tab should get closed itself otherwise there will be too many webstory tab opened.
- Pause and share icon should have more space between them.
- There should icon consistency in term of size as well as style in cross icon , next and previous icon.
- The loader icon after story ends looks like image right now please add animation to it with a contrasting color.
- Replace Web-Stories with Web Stories

2024-05-23 20:04 UTC, Hermione2408 commented on app/(default)/webstories/page.tsx
> +import { DummyData } from "./data"; // Import Data from data file
Please correct the variable name

2024-05-23 20:04 UTC, Hermione2408 commented on app/(default)/webstories/data.ts
please move this to utils

2024-05-23 20:04 UTC, Hermione2408 commented on app/(default)/webstories/[slug]/page.tsx
> +import { DummyData } from "../data";
please change the variable name

2024-05-23 20:04 UTC, Hermione2408 commented on app/(default)/webstories/[slug]/page.tsx
> +              <svg
It's better to not use svg directly in code as it get hard to identify which icon is it better to import it as component or SVG file

2024-05-23 20:04 UTC, Hermione2408 commented on components/utils/countingNumbers.tsx
> +          // console.log(data.stargazers_count);
you can remove this

2024-05-23 20:04 UTC, Hermione2408 commented on components/webstories/LottiePlayerWebStories.tsx
Instead of creating a whole new component can't we use the existing LottiePlayer Is there any issue with that?

2024-05-23 20:04 UTC, Hermione2408 commented on components/webstories/Readme.md
Is this file needed?

2024-05-23 20:04 UTC, Hermione2408 commented on components/webstories/Stories.tsx
> +  console.log("animatingDuration says hi from core:",animationDuration)
remove this console

2024-05-23 20:04 UTC, Hermione2408 commented on components/webstories/StoriesCards.tsx
> +          Discover what's going on in and around Keploy. Learn about Keploy and
Have you implemented tap right feature? If not we will need to change this line

2024-05-23 20:04 UTC, Hermione2408 commented on components/webstories/Webstories.tsx
> +              } mt-5 content-end text-sm text-center text-slate-200`}
We can increase the font size here, Also the link doesn't look clickable we can improvise that too

2024-05-23 20:04 UTC, Hermione2408 commented on components/webstories/components/Header.tsx
Why do we need to have a new header also when we are on web stories andif this is explicitly shown in web story page it doesn't need Web story in navbar

2024-05-23 20:04 UTC, Hermione2408 commented on public/images/testAndStubsGen.json
where is this file getting used?

2024-05-23 20:04 UTC, Hermione2408 commented on components/webstories/components/ShareComponent.tsx
> +            <p className=" font-bold justify-start mt-2">Share this webstories on these Platform</p>
change this line to - Share this web story on your favorite platforms

2024-05-24 04:32 UTC, Aditya-eddy commented on app/(default)/webstories/[slug]/page.tsx
> +import { DummyData } from "../data";
okay changed to DataFiles!

2024-05-24 04:36 UTC, Aditya-eddy commented on app/(default)/webstories/[slug]/page.tsx
> +              <svg
made another component for it!

2024-05-24 04:37 UTC, Aditya-eddy commented on app/(default)/webstories/page.tsx
> +import { DummyData } from "./data"; // Import Data from data file
Done!

2024-05-24 04:37 UTC, Aditya-eddy commented on components/utils/countingNumbers.tsx
> +          // console.log(data.stargazers_count);
Done!

2024-05-24 04:38 UTC, Aditya-eddy commented on components/webstories/Stories.tsx
> +  console.log("animatingDuration says hi from core:",animationDuration)
Done!

2024-05-24 04:39 UTC, Aditya-eddy commented on components/webstories/components/ShareComponent.tsx
> +            <p className=" font-bold justify-start mt-2">Share this webstories on these Platform</p>
okay!

2024-05-24 04:41 UTC, Aditya-eddy commented on public/images/testAndStubsGen.json
Was using this file for file formats for props will make a fix for it soon!

2024-05-24 05:00 UTC, Hermione2408 commented on public/images/testAndStubsGen.json
Didn't understand can you please elaborate?

2024-05-24 15:39 UTC, Aditya-eddy commented on public/images/testAndStubsGen.json
It was just used for giving props type. So that's why i used it removing it now.

2024-05-24 15:41 UTC, Aditya-eddy commented on components/webstories/components/Header.tsx
Because currently the homepage header does'nt offer the webstories panel. Are we planning to add it there.

2024-05-24 15:42 UTC, Aditya-eddy commented on components/webstories/StoriesCards.tsx
> +          Discover what's going on in and around Keploy. Learn about Keploy and
What is meant by tap right feature?

2024-05-24 15:45 UTC, Aditya-eddy commented on components/webstories/Webstories.tsx
> +              } mt-5 content-end text-sm text-center text-slate-200`}
I have scaled it to 125%. Also you mentioned that the cross button and prev and next button should have same style so should we follow the blue background or white background style.

2024-05-24 15:48 UTC, Aditya-eddy commented on app/(default)/webstories/data.ts
moved it into the Utils.

2024-05-24 15:52 UTC, Aditya-eddy commented on components/webstories/LottiePlayerWebStories.tsx
okay so there are 2 classNames that are to be added. One through props which will be applied to div containing the player and controls. One we have to add the className to the Player component. So player className is different for web-story use-case and the other use-case like in the landing-page. So i thought it would be better to create a new component it would be seprate and exclusive to web-stories.

2024-05-24 15:52 UTC, Aditya-eddy commented on components/webstories/Readme.md
I'll be writing the readme for the data.ts describing the data structure for it and I thought it can be usefull.

2024-05-27 10:24 UTC, Hermione2408 commented
Hey @Aditya-eddy great job on transition to next story! Please go through the following :

- The first page should contain heading only as it overlaps the title image - 
 ![Screenshot from 2024-05-27 11-05-32](https://github.com/keploy/website/assets/78696767/824769d6-c881-4f8a-bd87-7b14bc431bad)
 
- The button color looks good in blue background to me.

- Please change Web-stories to Web Stories here too and fix the height of the each card. 
![Screenshot from 2024-05-27 11-01-23](https://github.com/keploy/website/assets/78696767/7d3c9df6-b3a4-4b05-92f9-73eec0e4156b)

- The header and the webstory component has color difference please check that.

2024-06-03 10:25 UTC, charankamarapu reviewed
1. I think all web stories should be uniform below image shows that they are uneven right now.

<img width="1440" alt="Screenshot 2024-06-03 at 3 48 45 PM" src="https://github.com/keploy/website/assets/72094895/fcdf6b41-5630-4411-9cdc-cb87d0ecb2bf">

2. In the search bar the top margin is missing due to this it doesn't fell like a search bar.
<img width="1440" alt="Screenshot 2024-06-03 at 3 51 37 PM" src="https://github.com/keploy/website/assets/72094895/2a9ab3b0-92c6-4506-81d2-3ace9e3b86bf">

3. I think there should be a play button on the webstories which will indicate thats a video.

2024-06-03 10:27 UTC, charankamarapu commented
When press the next button continuously I am not able to navigate to next story.

2024-06-03 12:15 UTC, nehagup reviewed
@charankamarapu IMO to keep the repo light we can give @Aditya-eddy access to a public s3 bucket where he can upload the images and use the urls here.

2024-06-24 09:50 UTC, charankamarapu approved these changes
LGTM

2024-06-24 11:14 UTC, Hermione2408 approved these changes
LGTM!

2024-06-26 09:03 UTC, nehagup approved these changes

2024-06-26 09:04 UTC, nehagup commented
This is awesome @Aditya-eddy ! Kudos! 🎉

2024-06-26 09:04 UTC, merged

2024-06-26 09:05 UTC, Aditya-eddy commented
Thank you @nehagup , @charankamarapu  , @Hermione2408 I couldn't have done without you guys.