Language icons on home page point to their respective samples page
keploy/website pull request #56
Opened 2024-07-17 20:24 UTC by debayangg

Addresses [Issue #2090](https://github.com/keploy/keploy/issues/2090).

Makes the language icons on the home page clickable, redirects to the respective language's samples page. 

Current Behaviour:
![image](https://github.com/user-attachments/assets/16174ca9-dfcd-4635-a582-3f26df4aabb2)

Updated Behaviour:
![image](https://github.com/user-attachments/assets/d206d0a5-91a4-450d-8fd3-5102611a9dc4)

2024-07-17 20:29 UTC, debayangg commented
@Swpn0neel @Sonichigo pls review

2024-07-17 22:46 UTC, Swpn0neel approved these changes
LGTM!

2024-07-22 07:15 UTC, Hermione2408 requested changes
Hey @debayangg please change the java language url to https://keploy.io/docs/quickstart/pet-clinic/ 
and you should use the Link component from next/link for internal navigation, as it provides client-side navigation, which means the page transition is faster and the browser doesn't need to reload the page.

2024-07-23 09:53 UTC, Hermione2408 approved these changes
Build works fine, LGTM!

2024-07-23 13:31 UTC, merged