feat: added marquee animation
keploy/website pull request #68
Opened 2024-08-01 20:28 UTC by Aman172003

Closes [#2160](https://github.com/keploy/keploy/issues/2160)

https://github.com/user-attachments/assets/1e1de0dd-ff7a-469e-baa3-2107ec70371f

2024-08-03 08:41 UTC, Aman172003 commented
@Sonichigo review required!!

2024-08-04 08:13 UTC, Aditya-eddy commented
Hey @Aman172003 why did you change the package's version in package.json?

2024-08-05 09:40 UTC, Aman172003 commented
> Hey @Aman172003 why did you change the package's version in package.json?
> 

I was not able to use the marquee component with current version of eslint dependency.

2024-08-08 07:50 UTC, Aman172003 commented
@Aditya-eddy is there anything I need to change?

2024-08-08 10:05 UTC, nehagup requested changes
Thanks for the PR @Aman172003, I've requested some changes.

2024-08-08 10:05 UTC, nehagup commented on components/language.tsx
> +              {frameworks.map((framework, index) => (
It'll be better to keep the 2 unique lists and not repeat frameworks.

2024-08-08 10:05 UTC, nehagup commented on components/language.tsx
> +            <Link
there are linting changes added, please remove these.

2024-08-08 10:05 UTC, nehagup commented on tailwind.config.js
> +  content: [
Please remove linting changes.

2024-08-09 09:26 UTC, Aman172003 commented
Hey @nehagup mam, i have done all the required changes

2024-08-12 06:18 UTC, nehagup approved these changes
This looks good! Thanks @Aman172003 👏

2024-08-12 06:18 UTC, merged