Refactor: Make responsive community section
keploy/website pull request #7
Opened 2024-03-15 20:42 UTC by hanzili

fix [#1674](https://github.com/keploy/keploy/issues/1671)
1. make cards appear on the outer circular lines
<img width="698" alt="image" src="https://github.com/keploy/website/assets/96609857/741eae31-1ee2-4381-a7b2-ed6594f51bea">

2. Bunny image is now visible (small size) in the sm screen size at the top of the cards
<img width="428" alt="image" src="https://github.com/keploy/website/assets/96609857/6cecd8ec-18e3-4833-8ad4-ad0705cbe092">

3. add hover animation on cards
4. wasn't able to add parallax animation on the bunny image - the parallax effect requires changing the css properties of the bunny image based on scroll events. It requires additional logic to calculate the image's position dynamically, which easily conflict with the existing css for positioning cards around the bunny.

2024-03-18 17:04 UTC, Hermione2408 requested changes

2024-03-18 17:04 UTC, Hermione2408 commented on components/community.tsx
> +  svgIcon: any;
please avoid using any it's not a good practice

2024-03-18 18:31 UTC, hanzili commented on components/community.tsx
> +  svgIcon: any;
Agree! Since `svgIcon` is always going to be used as a url, I simply type it as a `string`.

2024-03-18 18:55 UTC, Hermione2408 approved these changes
LGTM @nehagup

2024-03-19 10:56 UTC, nehagup approved these changes
LGTM! 🫰

2024-03-19 10:57 UTC, merged