feat: add orbiting circles for community section on landing page
keploy/website pull request #88
Opened 2024-10-09 06:10 UTC by techmannih

close https://github.com/keploy/keploy/issues/2159
Issue https://github.com/keploy/keploy/issues/2159

@khareyash05 @Swpn0neel please review PR and merge it.

Now 

https://github.com/user-attachments/assets/4c964d85-ef01-481f-91de-a7d485c988bc

2024-10-09 06:24 UTC, Neeraj-gagat commented
Duplicate #87 
Bro you just copy pasted exact same changes I did. Exact word to word

2024-10-09 06:30 UTC, Neeraj-gagat commented
You just copy pasted exact same changes I did.

2024-10-12 12:22 UTC, techmannih commented
@khareyash05 please review

2024-10-14 09:14 UTC, khareyash05 requested changes
Could you please address the comment. Thanks

2024-10-14 18:04 UTC, techmannih commented
> You just copy pasted exact same changes I did.

please check once it's totally changed, @khareyash05 also check please

2024-10-14 18:06 UTC, closed without merging

2024-10-14 18:09 UTC, khareyash05 commented
Closing due to unaddressed comments

2024-10-15 01:53 UTC, techmannih commented
@khareyash05  Which comment did I not reply to? I am working on the issue. You can also check that this is not copied code.

2024-10-15 04:31 UTC, Sonichigo commented on components/community.tsx
> +        showExtraStyle ? "circle" : "w-[280px] mx-auto mb-5"
any specific for the 280px ?